name: $(SourceCollection)-$(Date:yyyyMMdd).$(Rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
- group: azdo

steps:

- checkout: self
  persistCredentials: true

- script: git clone https://github.com/joshjohanning/process-migrator
  displayName: clone repository
  workingDirectory: $(Pipeline.Workspace)

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: $(Pipeline.Workspace)/process-migrator

- script: | 
    cat <<< $(jq '.sourceAccountUrl = "https://dev.azure.com/$(SourceCollection)"' configuration.json) > configuration.json
    cat <<< $(jq '.sourceAccountToken = "$(PAT)"' configuration.json) > configuration.json
    cat <<< $(jq '.sourceProcessName = "$(sourceProcessName)"' configuration.json) > configuration.json
    cat <<< $(jq '.options["logLevel"] = "verbose"' configuration.json) > configuration.json
    cat configuration.json
  displayName: setup config
  workingDirectory: $(Pipeline.Workspace)/process-migrator

- script: |
    set -euxo pipefail
    node build/nodejs/nodejs/Main.js --mode=export
  displayName: 'run app'
  workingDirectory: $(Pipeline.Workspace)/process-migrator

# The following account needs contribute permissions on repository: "Project Collection Build Service Accounts"
- script: |
    mkdir -p $(SourceCollection)
    cp $(Pipeline.Workspace)/process-migrator/output/process.json ./$(SourceCollection)/$(sourceProcessName).json
    git config --global user.email "process-migrator@10thmagnitude.com"
    git config --global user.name "process-migrator"
    git config pull.ff only
    git pull origin HEAD:main
    git add .
    git commit -m "export from pipeline run $(Build.BuildNumber)"
    git push origin HEAD:main
  displayName: push to git repo
