name: $(SourceCollection)-$(Date:yyyyMMdd).$(Rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
  group: azdo

steps:

- script: git clone https://github.com/soccerjoshj07/process-migrator
  displayName: clone repository

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: process-migrator

- script: | 
    mv configuration.json configuration-temp.json
    jq '.sourceAccountUrl = "$(SourceCollection)"' configuration-temp.json > configuration.json
    jq '.sourceAccountToken = "$(pat)"' configuration-temp.json > configuration.json
    jq '.sourceProcessName = "$(sourceProcessName)"' configuration-temp.json > configuration.json
  displayName: setup config
  workingDirectory: process-migrator

- script: |
    node process-migrator/build/nodejs/nodejs/Main.js --mode export
    less process-migrator/output/processMigrator.log
  displayName: 'run app'

- script: |
    mkdir -p $(SourceCollection)
    cp process-migrator/output/process.json ./$(SourceCollection)
    git add .
    git commit -m "export from pipeline run $(SourceCollection)-$(Date:yyyyMMdd).$(Rev:r)"
    git push
  displayName: push to git repo
