name: import-$(SourceCollection)-$(Date:yyyyMMdd).$(Rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
- group: azdo

steps:

# - task: NodeTool@0
#   inputs:
#     versionSpec: '15.x'
#   displayName: 'Install Node.js'

- script: git clone https://github.com/soccerjoshj07/process-migrator
  displayName: clone repository
  workingDirectory: $(Pipeline.Workspace)

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: $(Pipeline.Workspace)/process-migrator

- script: | 
    cat <<< $(jq '.sourceAccountUrl = "https://dev.azure.com/$(SourceCollection)"' configuration.json) > configuration.json
    cat <<< $(jq '.sourceAccountToken = "$(PAT)"' configuration.json) > configuration.json
    cat <<< $(jq '.sourceProcessName = "$(sourceProcessName)"' configuration.json) > configuration.json
    # mv configuration.json configuration-temp.json
    # jq '.sourceAccountUrl = "$(SourceCollection)"' configuration-temp.json > configuration.json
    # jq '.sourceAccountToken = "$(pat)"' configuration-temp.json > configuration.json
    # jq '.sourceProcessName = "$(sourceProcessName)"' configuration-temp.json > configuration.json
    cat configuration.json
  displayName: setup config
  workingDirectory: $(Pipeline.Workspace)/process-migrator

- script: |
    node -v
    npm -v
    node build/nodejs/nodejs/Main.js --mode=export
    cat output/processMigrator.log
  displayName: 'run app'
  workingDirectory: $(Pipeline.Workspace)/process-migrator

- script: |
    mkdir -p $(SourceCollection)
    cp $(Pipeline.Workspace)/process-migrator/output/process.json ./$(SourceCollection)
    git config --global user.email "process-migrator@10thmagnitude.com"
    git config --global user.name "process-migrator"
    git add .
    git commit -m "export from pipeline run $(SourceCollection)-$(Date:yyyyMMdd).$(Rev:r)"
    git push
  displayName: push to git repo
